Enumerable
billodiallo/project2-enumerable pull request #1
Opened 2021-02-11 18:48 UTC by billodiallo

Create #my_each_with_index in the same way.
Create #my_select in the same way, though you may use #my_each in your definition (but not #each).
Create #my_all? (continue as above)
Create #my_any?
Create #my_none?
Create #my_count
Create #my_map
Create #my_inject

2021-02-11 22:29 UTC, enaburekhan requested changes
# Status: Request changes :full_moon:
**Hi team!
Great job on this milestone:clap::clap:. Your correct use of yield and self in the codebase is highly commendable:+1: . However, we just need to make a few changes in order to get this project approved.**
**Mandatory requirements**

- [ ] Fix the following errors for my_each_with_index by removing the square-bracket around the to_a[i] and it's index i.

  1) enumerables #my_each_with_index does not mutate the original array
     Failure/Error: array.my_each_with_index { |num| num + 1 }
     
     TypeError:
       no implicit conversion of Integer into Array
     ./enumerables.rb:19:in `my_each_with_index'

  2) enumerables #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self
     Failure/Error: let(:block) { proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } }
     
     NoMethodError:
       undefined method `<' for [4, 0]:Array
       Did you mean?  <<
      ./enumerables.rb:19:in `my_each_with_index'

  3) enumerables #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
     Failure/Error: let(:block) { proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } }
     
     NoMethodError:
       undefined method `<' for [5, 0]:Array
       Did you mean?  <<
      ./enumerables.rb:19:in `my_each_with_index'

- [ ] Fix the following failing tests on my_none?. 

  4) enumerables #my_none? returns true if the block never returns true for all elements
     Failure/Error: expect(array.my_none?(&true_block)).to eq(array.none?(&true_block))
     
     ArgumentError:
       tried to create Proc object without a block
      ./enumerables.rb:67:in `new'
      ./enumerables.rb:67:in `my_none?'
     
  5) enumerables #my_none? returns false if the block ever returns true for all elements
     Failure/Error: expect(array.my_none?(&false_block)).to eq(array.none?(&false_block))
     
     ArgumentError:
       tried to create Proc object without a block
     ./enumerables.rb:67:in `new'
      ./enumerables.rb:67:in `my_none?'

  6) enumerables #my_none? returns false if the block ever returns true for all elements::range
     Failure/Error: expect(range.my_none?(&false_block)).to eq(range.none?(&false_block))
     
     ArgumentError:
       tried to create Proc object without a block
      ./enumerables.rb:67:in `new'
      ./enumerables.rb:67:in `my_none?'

  7) enumerables #my_none? does not mutate the original array
     Failure/Error: array.my_none? { |num| num + 1 }
     
     ArgumentError:
       tried to create Proc object without a block
      ./enumerables.rb:67:in `new'
      ./enumerables.rb:67:in `my_none?'
    

  8) enumerables #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject
     Failure/Error: actual = multiply_els [2, 4, 5]
     
     NoMethodError:
       undefined method `multiply_els' for #<RSpec::ExampleGroups::Enumerables::MultiplyEls "accepts an array as an argument and multiplies all the elements of the array together using 
     my_inject" (./spec/enumerables_spec.rb:460)>
      ./spec/enumerables_spec.rb:461:in `block (3 levels) in <top (required)>'

Finished in 0.03808 seconds (files took 0.11186 seconds to load)
79 examples, 8 failures

Pls, check my comments below on the PR codebase for possible suggestions on how to fix the my_each_with_index and my_none? issues.

- [ ] Kindly improve the readme especially the getting started. Please check my comments on the PR codebase.

- [ ] In subsequent commits, use imperative tense for commit messages. Instead of, for example, **adding**, use **add**, instead of **updating**, use **update**

Make the above-required changes and when you are done, request for another review.
Kindly drop your questions :point_down: if you have any and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding :blush:
Eric Enaburekhan

2021-02-11 22:29 UTC, enaburekhan commented on README.md
> +5. Open a Pull Request
This should tell us how to clone and run the app into our local machine. You can start like so:
Clone the repository into your local machine using **the-repo-link** 
Cd into the cloned directory
...
run the "given command" say ruby enumerables.rb.
Kindly fix this by re-writing it.

2021-02-11 22:29 UTC, enaburekhan commented on enumerable.rb
> +      yield([to_a[i], i])
1) enumerables #my_each_with_index does not mutate the original array
     Failure/Error: array.my_each_with_index { |num| num + 1 }
     
     TypeError:
       no implicit conversion of Integer into Array
     # ./enumerables.rb:19:in `my_each_with_index'
    
Currently, this test and other my_each_with_index are not passing due to the code in line 19.
There is no need for the [] around to_a[i], i. You have already done the conversion to an array using the to_a[i].

2021-02-11 22:29 UTC, enaburekhan commented on enumerable.rb
> +      !my_any?(&Proc.new)
4) enumerables #my_none? returns true if the block never returns true for all elements
     Failure/Error: expect(array.my_none?(&true_block)).to eq(array.none?(&true_block))
     
     ArgumentError:
       tried to create Proc object without a block
     # ./enumerables.rb:67:in `new'
     # ./enumerables.rb:67:in `my_none?'
   
line 67 raises the error: tried to create Proc object without a block. You may have to refactor that line of code. You can use `&block` instead of Proc.new.

2021-02-12 08:52 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @billodiallo  & @enaburekhan**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] my_none? should return false if the block ever returns true for all elements::range

- [ ] my_none? when no block or argument is given should return false only if one of the collection members is true
- [ ] my_none? when a pattern other than Regex or a Class is given should return false only if one of the collection matches the pattern

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-02-12 14:15 UTC, billodiallo commented
hI @mahmoud717 
CHANGES DONE,kindly check again.

2021-02-12 20:14 UTC, SmithVyne approved these changes
Approved 👏 👏 
Hello, congratulations on making all the required changes requested by the previous TSEs. Your project is approved. You can now merge the branch and move further in the curriculum.

2021-02-12 20:31 UTC, merged